### ISSUE TITLE
Make the default currency be based on the quota setter, not the quota owner

### ISSUE THREAD

**Issue by alonkama** [ForceDotComLabs/QuotaEdit#10]
Based on [this comment](https://appexchange.salesforce.com/listingDetail?listingId=a0N3000000B41EqEAJ&revId=a0S3000000HpaLKEAZ&tab=r) from a user.

In a multi-currency org, there is a currency drop-down next to each user's quota. The dropdown's default value is that quota-carrying user's personal currency.

The request is to change that behavior, and make all the dropdown's defaults on that page be the *quota setter's* personal currency (the person who is visiting this page).

**Comment by alonkama** [comment]
Had to back out this change due to too many SOQLs (101). Need to fetch user default currency as part of getRoleSubordinateUsersMulticurrency().

**Comment by JmeG** [comment]
In the QuotaController class you are looping through a list of users and calling a method "getUserDefaultCurrency" which does a SOQL query.. so you are calling SOQL in a loop.

`
// Create blank quota records for all users
for (User user : forecastUsers) {
  System.debug('Name = ' + user.Name + ', Id=' + User.Id);
  QuotaModel quota = new QuotaModel();
  quota.ownerName = user.Name;
  quota.ownerId = user.Id;
  quota.startDate = startDate;
  quota.isQuantity = isQuantity();
  quota.currencyIsoCode = isMultiCurrencyOrg ? CurrencyUtil.getUserDefaultCurrency(quota.OwnerId) : null;
  quota.productFamily = isProductFamily() ? selectedPFString : null;
  quotaMapForFetch.put(user.Id, quota);
}`

**Comment by alonkama** [comment]
Yes, thanks, that's the problem area. Unfortunately to have this work correctly in multi-currency orgs requires a broader change. 

I backed out the problem area in version 1.8 of the app.

**Comment by JmeG** [comment]
I got it working in a sandbox by making these changes.

new method in CurrencyUtil.cls
``
public static Map<Id, String> getUsersDefaultCurrency(Set<Id> userIds) {
        // Can't use SOQL bracket syntax because it will not compile on mono-currency orgs
        List<SObject> sobjs = Database.query('SELECT DefaultCurrencyIsoCode FROM User WHERE Id IN :userIds');

        Map<Id, String> userCurrencyMap = new Map<Id, String>();
        for (SObject sobj : sobjs) {
            userCurrencyMap.put((Id)sobj.get('Id'), (String)sobj.get('DefaultCurrencyIsoCode'));
        }

        return userCurrencyMap;
    }
``

Updated getQuotasForPeriod method in QuotaController.cls
``
public List<QuotaModel> getQuotasForPeriod(Date startDate, Map<Id, QuotaModel> quotaMapForFetch) {

		List<User> forecastUsers = new List<User>();
		quotaMapForFetch.clear();

		// Someone with "View All Forecasts" and "Manage Quotas" should
		// be able to see and set the quotas of all the Forecasting Enabled
		// users.
		if (PermUtil.isReadWriteAll() || PermUtil.isReadOnlyAll()) {
			forecastUsers = [SELECT Id, Name FROM User WHERE IsActive = TRUE AND ForecastEnabled = TRUE LIMIT 999];
		}
		else if (PermUtil.isReadWriteBelowMe() || PermUtil.isReadOnlyBelowMe()) {
			// Traverse the role hierarchy and find all the subordinates.
			forecastUsers = RoleUtils.getRoleSubordinateUsers(Id.valueOf(UserInfo.getUserId()));
		}

		// Get default currency values for all forecast users
		Set<Id> forecastUserIds = (new Map<Id,User>(forecastUsers)).keySet();
		Map<Id, String> userDefaultCurrencyMap = CurrencyUtil.getUsersDefaultCurrency(forecastUserIds);

		// Create blank quota records for all users
		for (User user : forecastUsers) {
			System.debug('Name = ' + user.Name + ', Id=' + User.Id);
			QuotaModel quota = new QuotaModel();
			quota.ownerName = user.Name;
			quota.ownerId = user.Id;
			quota.startDate = startDate;
			quota.isQuantity = isQuantity();
			quota.currencyIsoCode = isMultiCurrencyOrg ? userDefaultCurrencyMap.get(user.Id) : null;
			quota.productFamily = isProductFamily() ? selectedPFString : null;
			quotaMapForFetch.put(user.Id, quota);
		}

		Set<Id> userIds = quotaMapForFetch.keySet();
		Boolean isQuant = isQuantity();
		String productFamilyStr = selectedPFString;

		// We have to use this clunky query creation, rather than using
		// the [SELECT... ] method, because if we reference CurrencyIsoCode
		// in a mono-currency org, we'll get a runtime error.
		String query = 'SELECT Id, QuotaOwnerId, PeriodId';

		if (isQuantity()) {
			query += ', QuotaQuantity';
		}
		else {
			query += ', QuotaAmount';
		}

		if (isMultiCurrencyOrg)
			query += ', CurrencyIsoCode';

		query += ' FROM ForecastingQuota WHERE QuotaOwnerId IN :userIds';
		query += ' AND StartDate=:startDate';
		query += ' AND isQuantity=:isQuant';
		query += ' AND ForecastingTypeId=:forecastingTypeId';


		if (isProductFamily()) {
			query += ' AND ProductFamily=:productFamilyStr';
		}
		else {
			query += ' AND ProductFamily=\'\'';
		}

		List<SObject> quotasFromDB = Database.query(query);

		for (SObject sobj : quotasFromDB) {
			Id userId = (Id) sobj.get('QuotaOwnerId');
			QuotaModel quota = quotaMapForFetch.get(userId);
			quota.quotaId = sobj.Id;
			quota.periodId = (String) sobj.get('PeriodId');
			quota.amount = (Double) sobj.get(isQuantity() ? 'QuotaQuantity' : 'QuotaAmount');
			quota.isQuantity = isQuantity();

			if (isMultiCurrencyOrg) {
				quota.currencyIsoCode = (String) sobj.get('CurrencyIsoCode');
			}
		}

		List<QuotaModel> ret = quotaMapForFetch.values();
		ret.sort();
		return ret;
	}
``

**Comment by alonkama** [comment]
Fixed in version 2.1
