### ISSUE TITLE
I want to do a data load to load all the Quotas. How can I achieve that?

### ISSUE THREAD

**Issue by vimarshkarbhari-okta** [ForceDotComLabs/QuotaEdit#14]
I want to use dataloader.io or some tool and load all the quotas from a CSV. How can I do that?

**Comment by dschach** [comment]
https://help.salesforce.com/HTViewHelpDoc?id=forecasts3_loading_quota_data.htm&language=en_US

Documentation has all the instructions.

**Comment by vimarshkarbhari-okta** [comment]
Thanks David. Also do you know how I can change visibility/access for forecast Quotas? Example: person X can see his quota and nothing else, his manager can see his quota and everyone under him and so on based on Role hierarchy?

**Comment by alonkama** [comment]
See the readme on what governs access to quotas: https://github.com/alonkama/QuotaEdit/blob/master/README.md
