### ISSUE TITLE
Only updating the quotas that are actually changed

### ISSUE THREAD

**Issue by corona2k** [ForceDotComLabs/QuotaEdit#15]
It looks like we are updating all of the records on the page. Is there any way that you can just look at the diff and update those?

**Comment by dschach** [comment]
That's an interesting request. Not unheard-of, but in my experience, a request like this usually has a specific use-case or reason why doing the full update is not optimal. Can you please provide some background? Thanks.

**Comment by alonkama** [comment]
There's no good way for me to find out which text fields were modified. It's actually more efficient to overwrite than it is to re-fetch the quota values from the server and do a comparison.

@corona2k is your concern that we're potentially overwriting more recent edits? I'm not optimizing this app for concurrent edits and frequently updated data: it's for monthly/quarterly quotas which shouldn't change so much.
