### ISSUE TITLE
Allowing Users to edit their own quota (including Partner Users)

### ISSUE THREAD

**Issue by jimrae** [ForceDotComLabs/QuotaEdit#16]
Is this supported? How would I have to configure the security? I have a partner portal, and when I expose the Edit Quota tab, the partner user gets "Insufficient Privileges".
My use case is that all partner users create their own "Budget" which is their estimated forecast, then, it is reviewed and approved by the partner managers. 
Rather than creating a custom object to temporarily store the quota, and then move it, I thought it would be easier if I could just let them edit the quota themselves.

**Comment by alonkama** [comment]
Unfortunately this is a built-in limitation in Collaborative Forecasts:
From https://help.salesforce.com/apex/HTViewHelpDoc?id=forecasts3_quotas_overview.htm&language=en_US :
 You can only edit direct subordinates’ quotas, and not your own; additionally, you must have the “Manage Quotas” permission.
