### ISSUE TITLE
Loading Quotas

### ISSUE THREAD

**Issue by barrybrownregalcinemas** [ForceDotComLabs/QuotaEdit#17]
Does it take some time to publish the quotas in salesforce?  I've loaded quotas in for several periods and hit submit, but they do not show up in the forecast. Any ideas?

**Comment by alonkama** [comment]
It should be immediate. Please ensure you're entering them for the correct period. If you're using quarterly forecasting, check the special handling you need to do.

**Comment by alonkama** [comment]
Barry, I'm closing this issue for now. If you're still experiencing problems, please reopen with more details.
