### ISSUE TITLE
quota loading

### ISSUE THREAD

**Issue by skaiser22** [ForceDotComLabs/QuotaEdit#18]
When you enter the quotas using quarterly forecasting, it says use the beginning month of each quarter and leave the other months blank. When you do this and then go to the forecasting tool in SF, it does give you the ability to see where you are at vs your overall quota , but when you go into each month... if there is not a quota listed, it does not pick it up in the forecasting category. 
Example:
Edit Quota set as follows:
Q1 = 348K
Q2 = 204K
Overall quota is 1.2M and the top row is taking the overall percentage and that appears normal. But under close won on the fourth row it show he attained 72,500 in March but – shows up as the percentage? But it does show 6% at the very top. Also in row 5, he has a quote for Q2 = 204k and a pipeline of 319K so it show the percentage. It looks odd to only have the percentage show up on the rows that have quarterly quotas. Any fix to this?
![image](https://cloud.githubusercontent.com/assets/12209703/7441145/125a3128-f0a9-11e4-97ca-ab3c54499ac1.png)

**Comment by skaiser22** [comment]
If I breakout the quarterly by month it does calculate but it also shows odd:
![image](https://cloud.githubusercontent.com/assets/12209703/7441180/535eb5ee-f0aa-11e4-8a43-3e519669ad2e.png)
Wouldnt it be less confusing to have the main % just show like you have on row 1 and no other percentages show on other rows since it calculates different?

**Comment by alonkama** [comment]
Hi @skaiser22 ,
It's up to the admin to configure whether Collaborative Forecasts is using quarterly vs monthly forecasts. The quotas follow suit. So you can't have quarterly quotas but still forecast by month.

The Edit Quotas tool can't read the organization's metadata, so it can't determine which setting. This is the reason for the workaround on the page, where if you're using quarterly forecasts then you enter them on the month that represents the start of that quarter.

Feel free to reopen if you have more questions.
