### ISSUE TITLE
Question on Forecasting/Quota

### ISSUE THREAD

**Issue by karengreyes** [ForceDotComLabs/QuotaEdit#20]
Hi!

In our org, we input monthly quotas for different users, including one manager. However, in the Forecasting tab, this manager's quota does not show up in her row (so the Quota field is blank). Instead, it shows up as the quota for her team. 

Can you please advise how we can make a quota reflect on a manager's record and not become the rollup quota for her team?

Thanks!

**Comment by alonkama** [comment]
Collaborative Forecasts assigns a single quota to a manager. It is unrelated to this AppExchange app.
From https://help.salesforce.com/HTViewHelpDoc?id=forecasts3_quotas_overview.htm&language=en_US : 
A manager’s quota equals the amount the manager and team are expected to generate together.
