### ISSUE TITLE
edit Quotas App

### ISSUE THREAD

**Issue by meytalL** [ForceDotComLabs/QuotaEdit#22]
Hi,
I download the app for specific profiles but i'm getting no permission error when login in their name.
what should i do?

Thanks

**Comment by alonkama** [comment]
@meytalL have you configured your user and profile permissions based on [this guide]( https://help.salesforce.com/apex/HTViewHelpDoc?id=forecasts3_enabling_quotas_in_forecasts.htm&language=en_US#topic-title)? It's not sufficient to install the app - you must have the proper settings configured in Salesforce.

What error message are you seeing?

**Comment by meytalL** [comment]
Hi,
I found the problem and now it is working.
Thank you for your help 
and good day
