### ISSUE TITLE
Creating Reports from Quotas

### ISSUE THREAD

**Issue by jmcguire1978** [ForceDotComLabs/QuotaEdit#23]
Hi there.  First off, I love your App.  I do have a question regarding reporting on Quotas.

How do I run a report that pulls in quota?  Essentially I'm asking where that quota number is stored and how I access it in reports.  I want to create two reports.  One that is MTD vs Quota and the other which is YTD vs quota.

Any help would be greatly appreciated!

Jake

**Comment by alonkama** [comment]
Hi Jake, thank you for using the app.
Check out the Collaborative Forecasts Implementation Guide at http://resources.docs.salesforce.com/198/0/en-us/sfdc/pdf/forecasts.pdf . Starting from page 24, it explains how to create a Custom Report Type, and walks through an example of creating a quota attainment report.

Hope this helps.

-Alon.
