### ISSUE TITLE
problem installing to sandbox

### ISSUE THREAD

**Issue by cherylzimmermann** [ForceDotComLabs/QuotaEdit#24]
Object type 'ForecastingType' is not supported. If you are attempting to use a custom object, be sure to append the '__c' after the entity name. Please reference your WSDL or the describe call for the appropriate names.

**Comment by alonkama** [comment]
Cheryl,

This error indicates that Collaborative Forecasts is not enabled in this
sandbox. Can you confirm that you can see the Forecasts tab? And that you
haven't enabled the older Customizable Forecasts? This app is not
compatible with the older forecasting.

On Dec 19, 2015, at 11:16 AM, cherylzimmermann <notifications@github.com>
wrote:

Object type 'ForecastingType' is not supported If you are attempting to use
a custom object, be sure to append the '__c' after the entity name Please
reference your WSDL or the describe call for the appropriate names

—
Reply to this email directly or view it on GitHub
<https://github.com/ForceDotComLabs/QuotaEdit/issues/24>.

**Comment by cherylzimmermann** [comment]
you're right I didn't have it enabled in my sandbox, I think that corrected
my issue. Thanks.

*cheryl zimmermann *director of marketing services
lamar advertising co.  |  5321 corporate blvd.
baton rouge, la 70808  |  ph: 800.235.2627
