### ISSUE TITLE
fail on install

### ISSUE THREAD

**Issue by berjakian** [ForceDotComLabs/QuotaEdit#25]
http://www.screencast.com/t/cvwJfvugfp
"forecasting type not supported"
i read some of your other posts about supporting collaborative and not customizable forecasting... sorry, i don't yet understand the diff.

any advice?
thanks,
b

**Comment by berjakian** [comment]
http://www.screencast.com/t/E4SEwruF

so i guess i have customizable forecasting...

**Comment by alonkama** [comment]
Thanks for the screenshot. Yes, you're using the older generation of Forecasting. It's incompatible with this app.

**Comment by berjakian** [comment]
Hey Alon,

Any advice? Should I switch?

This link doesn’t help…
https://help.salesforce.com/HTViewHelpDoc?id=faq_forecasts3_whats_difference_between_versions.htm&language=en_US

This one is a bit better… but still makes them both sound like good options…
https://blogs.perficient.com/salesforce/2014/01/13/salesforce-collaborative-forecasts-or-customizable-forecasts-how-to-pick-which-one-is-best-for-your-organization/


Background

  *   calendar fiscal
  *   6 sales reps are allocated handful of states each
  *   Sales reps have quarterly quotas… just a simple revenue number… no product or quantity detail needed
  *   Opportunities are categorized into the following confidence levels
     *   A: 90%+ confidence… aka forecast category
     *   B: 75% confidence… aka upside category
     *   C: 50% confidence… aka pipeline category

what I need…

  *   At any time I’d like to see a Forecast Report showing how well reps are tracking to their quarterly quota goals…
     *   To do that, I would expect a table… a row for each rep… and the following columns…
        *   $ Quota…
        *   $ Closed Won Opps…
        *   $ ‘A’ Category Opps…
        *   $ Subtotal of Closed Won + A
        *   $ Variance of Subtotal from Quota

Nice to haves…

  *   Show ‘B’ Opps in the above Forecast Report… in their own column
  *   I’d like to define quota to the rep and apportion it by specific geo within their allotted territory…. (e.g. Jason has florida, texas and some other states… I’d like to assign a sales quota for jason and then break it down by florida, texas, and ‘other states’)

Thanks for any advice…


_____________________
Berj Akian, CEO
Cell: 201-745-1999<tel:201-745-1999>
berj@classlink.com<mailto:berj@classlink.com>

Tel: 888-963-7550 x1503<tel:888-963-7550;1503>
www.ClassLink.com<http://www.classlink.com/>

To schedule a time with me...
https://my.timedriver.com/TWD2M

From: Alon Kama
Reply-To: ForceDotComLabs/QuotaEdit
Date: Tuesday, December 29, 2015 at 4:11 PM
To: ForceDotComLabs/QuotaEdit
Cc: Berj Akian
Subject: Re: [QuotaEdit] fail on install (#25)


Thanks for the screenshot. Yes, you're using the older generation of Forecasting. It's incompatible with this app.

**Comment by alonkama** [comment]
I think you can accomplish your must-haves with Collaborative Forecasts. Geo-based quotas are not available in either option. 
Keep in mind that active development is only occurring on Collaborative Forecasts. So unless you need a particular feature only found in Customizable, I recommend switching. Try it out in a sandbox first to see if it suits your needs.

**Comment by berjakian** [comment]
Thanks.

I need SF to do it for me right?
I can’t switch it myself?

From: Alon Kama
Reply-To: ForceDotComLabs/QuotaEdit
Date: Tuesday, December 29, 2015 at 5:20 PM
To: ForceDotComLabs/QuotaEdit
Cc: Berj Akian
Subject: Re: [QuotaEdit] fail on install (#25)


I think you can accomplish your must-haves with Collaborative Forecasts. Geo-based quotas are not available in either option.
Keep in mind that active development is only occurring on Collaborative Forecasts. So unless you need a particular feature only found in Customizable, I recommend switching. Try it out in a sandbox first to see if it suits your needs.

**Comment by alonkama** [comment]
Yes, you need to contact Support and ask to switch.
