### ISSUE TITLE
Insufficiant privileges

### ISSUE THREAD

**Issue by pcabessa** [ForceDotComLabs/QuotaEdit#26]
Hello,
Although we gave the user profil the permission to "Manage quotas", the user gets the "Insufficiant privileges" error message when clicking on the tab "Edit Quotas".
Did we miss something?
Thanks.

**Comment by alonkama** [comment]
Is the problem localized to a particular user? Are the admin and other Forecasting users able to see the tab?
When installing the package, was the option selected to install "for All Users" or just to admins or a specific profile?
Please review https://help.salesforce.com/apex/HTViewHelpDoc?id=distribution_installing_packages.htm for troubleshooting tips.

**Comment by pcabessa** [comment]
The IT team says they installed it for all users.
At the moment, only the admin can enter the tab. The other profiles get the
insufficiant privileges messages.
Thanks for your help,

Philip Cabessa
Customer Success Executive | Salesforce
3 avenue Octave Gréard
75007 Paris
Tel. +33 (0)6 12 35 56 88

<http://salesforce.com/fr/signature>//

2016-01-21 15:49 GMT+01:00 Alon Kama <notifications@github.com>:

**Comment by alonkama** [comment]
Can the user provide a screenshot of the error?
I'm glad to hear that the admin can access it. Can they verify if the user (or their profile) has permission/access to the Tab?

**Comment by pcabessa** [comment]
The IT developer has a doubt about the fact he gave access to all users.
Maybe I should desinstall the app and install it again?
Here is the snapshot anyway:
[image: Images intégrées 1]

Philip Cabessa
Customer Success Executive | Salesforce
3 avenue Octave Gréard
75007 Paris
Tel. +33 (0)6 12 35 56 88

<http://salesforce.com/fr/signature>//

2016-01-21 16:18 GMT+01:00 Alon Kama <notifications@github.com>:

**Comment by alonkama** [comment]
The attachment did not come through.
Anyhow, there's no harm in reinstalling.

**Comment by pcabessa** [comment]
Hello,
I reinstalled the package and it works now!
I wanted to ask you also if for French customers, you offer screens in
French.
Thanks!

Philip Cabessa
Customer Success Executive | Salesforce
3 avenue Octave Gréard
75007 Paris
Tel. +33 (0)6 12 35 56 88

<http://salesforce.com/fr/signature>//

2016-01-21 17:40 GMT+01:00 Alon Kama <notifications@github.com>:

**Comment by alonkama** [comment]
I'm glad it's working now!
The app has been internationalized, but I haven't made any specific translations. If the customer is willing to translate the following labels, I'd be happy to incorporate them into the app:
https://github.com/ForceDotComLabs/QuotaEdit/blob/master/src/labels/CustomLabels.labels

**Comment by pcabessa** [comment]
Great!
Could you provide me with a list of labels so that I give you the
translations?

Philip Cabessa
Customer Success Executive | Salesforce
3 avenue Octave Gréard
75007 Paris
Tel. +33 (0)6 12 35 56 88

<http://salesforce.com/fr/signature>//

2016-01-22 15:52 GMT+01:00 Alon Kama <notifications@github.com>:

**Comment by alonkama** [comment]
Philip, the labels are at the following URL:

https://github.com/ForceDotComLabs/QuotaEdit/blob/master/src/labels/CustomLabels.labels

**Comment by pcabessa** [comment]
Sorry! Here are the translations in French:

Copy the above quota to another time period = Copier les quotas ci-dessus
vers une autre période

Leave the other months blank = Laisser les autres mois vides

Products not categorized = Produits sans catégorie

Quantity = Quantité

If Quarterly Forecasting is enabled, please edit the quota using the start
month only = Si les Prévisions Trimestrielles sont activées, saisir
uniquement le quota sur le mois de début

To enter a quarterly forecast, choose the beginning month of the quarter.
For example, if the fiscal year starts in February = Pour saisir une
prévision trimestrielle, choisir le mois de début du trimestre. Par
exemple, si l'année fiscale débute en février

You do not have permission to view quotas = Vous n'avez pas la permission
de voir les quotas

You have permission to view and edit quotas for all Forecast Enabled users
= Vous avez la permission de lire et modifier les quotas pour tous les
utilisateurs de Prévisions autorisés

You have permission to view and edit quotas for Forecast Enabled users in
your forecasting hierarchy = Vous avez la permission de lire et modifier
les quotas pour les utilisateurs de Prévisions autorisés dans votre
hiérarchie de prévisions

You have permission to view quotas for all Forecast Enabled users, but no
write permission = Vous avez la permission de lire les quotas pour tous les
utilisateurs de Prévisions autorisés, mais vous n'avez pas la permission de
les modifier

You have permission to view (not edit) quotas for Forecast Enabled users in
your forecasting hierarchy = Vous avez la permission de lire (non modifier)
les quotas pour les utilisateurs de Prévisions autorisés dans votre
hiérarchie de prévisions

Quotas for period starting = Quotas pour la période démarrant le

Revenue = Chiffre d'affaires

Select starting month = Sélectionner le mois de début

(refreshing...) = (rafraîchissement...)

Using quarterly forecasts? = Utilisation des prévisions trimestrielles ?

Philip Cabessa
Customer Success Executive | Salesforce
3 avenue Octave Gréard
75007 Paris
Tel. +33 (0)6 12 35 56 88

<http://salesforce.com/fr/signature>//

2016-01-22 16:09 GMT+01:00 Alon Kama <notifications@github.com>:

**Comment by alonkama** [comment]
Thank you! I'm tracking it as a separate issue in #27. Hopefully will get to it in the coming weeks.
