### ISSUE TITLE
Can a manager edit his own quota?

### ISSUE THREAD

**Issue by pcabessa** [ForceDotComLabs/QuotaEdit#29]
As you know, quotas do not roll up the hierarchy, so when a manager edits the quotas of his sales team, his quotas remain empty.
Would there be a way to give him the right to edit his own quota (for instance to sum the quotas of his sales reps)?
Thanks!

**Comment by alonkama** [comment]
Collaborative Forecasts does not allow users to edit their own quotas, unless they have the permission to View All Forecasts. For more info on quota permissions, see  https://help.salesforce.com/apex/HTViewHelpDoc?id=forecasts3_enabling_quotas_in_forecasts.htm&language=en_US or the README file on https://github.com/ForceDotComLabs/QuotaEdit . This app can't work around this limitation.
