### ISSUE TITLE
Running Test class in production generates DUPLICATE_VALUE error

### ISSUE THREAD

**Issue by jimrae** [ForceDotComLabs/QuotaEdit#31]
When I run the QuotaControlTest Test class in my production org, I get this error on the "updateQuotas" test:
**EXCEPTION_THROWN [292]|System.DmlException: Upsert failed. First exception on row 13; first error: DUPLICATE_VALUE, duplicate value found: <unknown> duplicates value on record with id: <unknown>: []**

This is occurring when I am upserting the ForecastQuota list.  I have traced the Debug statement at line 287 "going to save this quota:" and it has a unique owner for each record getting upserted.

Any ideas?

**Comment by alonkama** [comment]
Sorry, haven't gotten to this yet. Please consider submitting a pulling request.
