### ISSUE TITLE
Cannot view currency options

### ISSUE THREAD

**Issue by NancyFrank** [ForceDotComLabs/QuotaEdit#42]
Nor can I view the Product Forecasting in our Org.

**Comment by alonkama** [comment]
Please ensure that you have:
1. Product Family Forecasting enabled (a specific Forecasting Type configured for this in the Forecasting Setup page)
2. Multi-currency turned on for this org. If you don't see multiple currencies on your Forecasting page, then you won't see multicurrency quotas in this app.

If you have these, please reopen with some screenshots of what you can see.

**Comment by NancyFrank** [comment]
I do have both of these things enabled.
But I cannot see currencies in Edit Quotas. [cid:image002.png@01D18E83.730FF2A0]

[cid:image001.png@01D18E80.EEC597E0]

**Comment by alonkama** [comment]
The images did not go through by email. Please add it directly at https://github.com/ForceDotComLabs/QuotaEdit/issues/42 .

If you could, please get a screenshot of the Edit Quotas app as well as Forecasting main page.

**Comment by NancyFrank** [comment]
![editquotascapture](https://cloud.githubusercontent.com/assets/18267639/14261657/400ba5c4-fa77-11e5-835d-1889686797e8.PNG)

**Comment by alonkama** [comment]
Thank you for the screenshot. This looks like a legitimate problem for the Edit Quotas app. Would you mind including a Debug Log? You can generate one by going to Setup->Logs->Debug Logs and setting up a trace, then refreshing the page for the Edit Quotas app. You can upload it here or email me at akama@salesforce.com . Thanks.

**Comment by NancyFrank** [comment]
Of course.  Thanks.
[DebugLogNFranklin.txt](https://github.com/ForceDotComLabs/QuotaEdit/files/203352/DebugLogNFranklin.txt)

**Comment by NancyFrank** [comment]
Any resolutions?

**Comment by alonkama** [comment]
Thanks for the log. This looks like a legitimate issue. The order in which the Forecasting Types were created is influencing the drop-down. I apologize for the inconvenience.

I don't see a workaround except deleting the Forecasting Types and creating the one for Product Family first. But this is likely not a viable option, as overrides and comments are erased when deleting a forecasting type. 

A new version of the app (2.0) with a completely refactored drop-down will be released in the next few weeks. I will ensure that your flow is tested. I will update you once it is ready and would appreciate your feedback on whether it's working correctly.

**Comment by NancyFrank** [comment]
I sincerely appreciate this and will be glad to test the new version – it definitely will help us if this can be done successfully.  Thanks.

**Comment by NancyFrank** [comment]
Alon, Has the new version of the app (2.0) been released yet.  I appreciate your help on this.  The team that need the product quotas is deploying to Sandbox Monday the 18th, so there is a little time but not much.  Will definitely give you requested feedback.  Let me know and Thanks again.

**Comment by alonkama** [comment]
Hi Nancy, I'm working on the app at this very minute. But it's a big rewrite and will take more time.
If this is a new deployment, then you may have a workaround. Just define the Product Family forecast as the first forecasting type. I'm fairly sure that will work.

**Comment by NancyFrank** [comment]
Thank you.  We may have one group already using the Opportunity Revenue.  I will check that first.

**Comment by NancyFrank** [comment]
Hi Alon,

I was looking at the dependencies for the app and the various components – I’m not a developer, so I look but do not edit.  I noticed that the Permission Set for Edit Quotas did not contain the Visualforce page or all the Apex Classes needed for multi-currency or Products, so I enabled them in the Permission Set.  As System Administrator, I have all of these enabled, but until I added them to the permission set, I could not see these views.  Bottom line is, I can now see the Edit Quotas page with currency option, the Product Quantity and the Product Revenue.  Does this mean my issues does not exist or is resolved?  I was very happy to see these interfaces.

**Comment by alonkama** [comment]
That's interesting. I thought that you had access to the Edit Quotas page already, and were just experiencing a problem with the Product Family selector. If you're able to see the page and toggle between Forecasting Types and Product Families, then your issue is likely resolved. Please let me know.

**Comment by NancyFrank** [comment]
I did have access to the tab in my profile – System Administrator.  All of the settings were in place in my System Administrator profile settings, apex classes and vf pages.  I could see the Edit Quotas tab even without the permission set .

What I found is that – in the Permission Set – these apex classes and vf pages were not enabled, only Opportunity Revenue.  I enabled them and now I can see all of it – including the multi-currency option that I could not see before.  The team that installed this suggested that I add the permission set to my permissions.  They had not enabled these other views.

Thanks for your help.  Is there a log or report of some kind that I can run to show you the progression of these steps?

**Comment by alonkama** [comment]
Thanks for the details. I can't think of an audit trail that you can safely share. 
So my takeaway is to create a Permission Set in order to have the install work correctly for non-admins.
I'm glad this is now working out for you. I'll go ahead and close out this ticket.

**Comment by NancyFrank** [comment]
Thank you so much for your attention to this.
