### ISSUE TITLE
How to I set up a roll up quota for management based on current managers without losing the history if they switch teams?

### ISSUE THREAD

**Issue by cookimnstr13** [ForceDotComLabs/QuotaEdit#44]

**Comment by alonkama** [comment]
This app is separate from Salesforce's Collaborative Forecasts offering. I suggest that you consult the Help & Training or file a case.

A forecast is assigned to an individual - there is no roll-up of the quota. A quota is per-period and a history of prior quotas can always be accessed via reports.
