### ISSUE TITLE
Error when creating or editing existing quotas

### ISSUE THREAD

**Issue by robrookeceterna** [ForceDotComLabs/QuotaEdit#46]
Recieving error message: If Quarterly Forecasting is enabled, please select "Quarter" from the options above before attempting to add quotas.

It still allows me to create new quotas, but seems to return the error when selecting quarterly even though my forecast is set to quarterly. 

Any help appreciated

**Comment by alonkama** [comment]
Are you using Quarterly or Monthly forecasts in your org? 

It's a limitation of the Salesforce API that makes it not possible to determine which period type you're using. 

If using the wrong type, the quotas will still be created. For example, if your org is Quarterly but you created a quota for February, that quota will be inserted for Q1.

Please go to the Forecast tab and find the period in which the quota was entered. I'm fairly certain that it's already there.

**Comment by robrookeceterna** [comment]
Hi,

Thanks for the reply,

We are using Quarterly and the error only appears when selecting quarterly
from the edit quotas object. The quota is created, but having to click
submit twice every time a value is entered or updated isn't ideal.  Weirdly
it seems to work when selecting monthly, without returning an error, even
if my forecast is set to quarterly.
Any thoughts?

On 14 June 2016 at 17:32, Alon Kama <notifications@github.com> wrote:

> Are you using Quarterly or Monthly forecasts in your org?
>
> It's a limitation of the Salesforce API that makes it not possible to
> determine which period type you're using.
>
> If using the wrong type, the quotas will still be created. For example, if
> your org is Quarterly but you created a quota for February, that quota will
> be inserted for Q1.
>
> Please go to the Forecast tab and find the period in which the quota was
> entered. I'm fairly certain that it's already there.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ForceDotComLabs/QuotaEdit/issues/46#issuecomment-225939018>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATAsOY6y3AcyoxPHR6-a_RgTkfs1uX9pks5qLtewgaJpZM4I1gl0>
> .
>



-- 
-- 
Best Regards,

Rob Rooke
Consultant
*M:* +44 (0)7920449059 <%2B44%20%280%29%207920%20449%20059>
*O:* +44 (0) 203 011 5605 <%2B44%20%280%29%20203%20011%205421>
*E: *rob@ceterna.com
<https://www.ceterna.com/>*W:* www.ceterna.com <http://www.ceterna.com/>
*A:* Ceterna Ltd, 4.1 Union Court, 20-22 Union Road, Clapham, London, SW4
6JP <https://goo.gl/maps/cJXs5>



<https://www.linkedin.com/company/ceterna>
Confidentiality & Disclaimer This e-mail is intended only for the addressee
named above and the contents should not be disclosed to any other person
nor copies taken. If you are not the intended receipient you must not use,
disclose, distribute, copy, print, or rely on this e-mail. Any views or
opinions presented are solely those of the  sender and do not necessarily
represent those of Ceterna Ltd, unless otherwise specifically stated. As
Internet communications are not secure we do not accept legal
responsibility for the contents of this message, nor responsibility for any
change made this to this message after it was sent by the original sender.
We advise you to carry out your own virus check before opening any
attachment as we cannot accept liability for any damage sustained, as a
result of any software viruses. <http://www.ceterna.com/>

**Comment by alonkama** [comment]
The app is heavily refactored in version 2.1 (updated today). Could you upgrade to it and retry? Please reopen the case if the issue persists.
