### ISSUE TITLE
entered quotas, what's next?

### ISSUE THREAD

**Issue by joalouleo** [ForceDotComLabs/QuotaEdit#47]
I downloaded this in my demo environment and I can't find any documentation on what to do next or how this works.    I want to be able to give access to my Sales VPs to enter in their reps Quotas, and for them to see how sales reps are doing against their quota through out the quarter through and see the results at the end of the quarter.  Is this possible?  The way I am looking at this now is just a place where I can add Quota numbers but nothing else.

Are these Quotas available in reports and can they be used in dashboards?
Are they able to be adjusted during the quarter?
Can the quotas be rolled up by Owner Roles?

Is there any documentation that I can read how to set this up.    Please help!

Thanks!
-Joanna

**Comment by alonkama** [comment]
Hi Joanna,

See the [AppExchange listing](https://appexchange.salesforce.com/listingDetail?listingId=a0N3000000B41EqEAJ) for more information. This package doesn't introduce the concept of Quotas - they're already a part of Collaborative Forecasts. It only gives the user a UI in which to edit quotas, in place of uploading them via API.
