### ISSUE TITLE
How to download previous version (1.8)?

### ISSUE THREAD

**Issue by danielzorzi** [ForceDotComLabs/QuotaEdit#48]
Hello, the customer does not want to use this newest version (2.0) because several usability constraints.
   Thus, we would like to know how to download the previous vesion (1.8)?

  Thanks,

**Comment by alonkama** [comment]
I'm looking into it. It wasn't my intention to have 2.0 up yet.

**Comment by danielzorzi** [comment]
Hi Alon, did you have some return? This issue became critical to the customer and we need provide a faster answer...

Thanks,

**Comment by alonkama** [comment]
I've reached out to Salesforce Labs to help me resolve this issue.
If the customer needs a workaround, I recommend pulling this project from Github and deploying it to their org.
Also, any quota editing can be done using API.

**Comment by danielzorzi** [comment]
Is there a compiled version? Or only the source codes?

**Comment by alonkama** [comment]
Actually, please have them try this workaround:
1. Uninstall the v2.0 app
2. Direct install version 1.8 via this link: https://login.salesforce.com/packaging/installPackage.apexp?p0=04ti00000015aK5

**Comment by danielzorzi** [comment]
Thanks Alon, we got this version and installed it successfully!

Regards, Daniel.

**Comment by alonkama** [comment]
Watch for version 2.1, coming out in the next couple of days.
