### ISSUE TITLE
Question about Salesforce TLS 1.0 Disablement Compliance

### ISSUE THREAD

**Issue by mikelam2015** [ForceDotComLabs/QuotaEdit#49]
Hi, 
Is the latest version of the package compliant about Salesforce TLS 1.0 Disablement? Thank you.

**Comment by alonkama** [comment]
Yes, though I haven't explicitly tested it.  It's 100% on the platform and makes no callouts, so there shouldn't be an issue. 

If you're validating your org for compliance, I suggest you install it in a Sandbox that has TLS 1.0 disabled and ensure that everything works as expected.

**Comment by alonkama** [comment]
I just tested with an org that disables TLS 1.0. The app is working fine, so I'm calling it compliant.
