### ISSUE TITLE
Not able to install the app in SBX

### ISSUE THREAD

**Issue by mostlysummer** [ForceDotComLabs/QuotaEdit#50]
I receive this error message when trying to install the app in SBX

Your request to install package "Edit Quotas 2.1" was unsuccessful. None of the data or setup information in your salesforce.com organization was affected.

If your install continues to fail, contact Salesforce CRM Support through your normal channels and provide the following information.

Organization: MobileCause (00Dn00000000ZWV)
User: Agneta Ormos (005F0000005d8WE)
Package: Edit Quotas (04ti00000011PQK)
Error Number: 108048988-7068 (1636627951)
Problem:

1. (CalendarUtil) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
CalendarUtil: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

2. (CurrencyUtil) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
CurrencyUtil: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

3. (ForecastingTypeUtil) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
ForecastingTypeUtil: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

4. (LoadQuotasModel) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
LoadQuotasModel: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

5. (PermUtil) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
PermUtil: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

6. (ProductFamilyUtil) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
ProductFamilyUtil: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

7. (QuotaControllTest) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
QuotaControllTest: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

8. (QuotaController) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
QuotaController: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

9. (QuotaModel) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
QuotaModel: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

10. (RoleNodeModel) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
RoleNodeModel: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

11. (RoleUtils) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
RoleUtils: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

12. (TreeViewController) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
TreeViewController: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

13.  Apex class 'EditQuotas.TreeViewController' does not exist
TreeView: Apex class 'EditQuotas.TreeViewController' does not exist

14.  Apex class 'EditQuotas.TreeViewController' does not exist
QuotaEdit: Apex class 'EditQuotas.TreeViewController' does not exist

15. (Edit_Quotas_access) In field: apexClass - no ApexClass named QuotaModel found
Edit_Quotas_access: In field: apexClass - no ApexClass named QuotaModel found

**Comment by alonkama** [comment]
Yeah, it's a very cryptic error message.
It's indicating that this org does not have Collaborative Forecasts enabled on it. Could you please check that it's on by going to the Forecasts Settings in Setup?

**Comment by mostlysummer** [comment]
it's enabled

**Comment by alonkama** [comment]
This message

> Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

suggests that the API cannot find the object called ForecastingItem , which is part of Collaborative Forecasts. Can you confirm that you have at least one Forecasting Type defined, and that you can see the Forecasting grid correctly as a user?

**Comment by mostlysummer** [comment]
Yes, I have the Forecast Type = Opportunities (Revenue) enabled and I can see the grid as a user

**Comment by alonkama** [comment]
I'm still puzzled about why it's not working.
I see that you've only attempted this install once - is that correct? Would you mind retrying?
