### ISSUE TITLE
Managers can't see subordinates quotas on Edit Quotas

### ISSUE THREAD

**Issue by Karinleigh** [ForceDotComLabs/QuotaEdit#51]
Hi there - 

I am trying to figure out why managers can't see others quota data on my Actual vs. Quota reports. They see their own but not any of their subordinates. As a system admin, I can see all. 
What am I doing wrong?

Thanks,

Karin

**Comment by alonkama** [comment]
Karin, have you reviewed the permissions required on this help doc? https://help.salesforce.com/articleView?id=forecasts3_enabling_quotas_in_forecasts.htm

You need to grant Manage Quotas permissions to those managers.
