### ISSUE TITLE
TLS 1.0 Disablement Compliant?

### ISSUE THREAD

**Issue by mikelam2015** [ForceDotComLabs/QuotaEdit#52]
Hi, 

Is this app compliant to the TLS 1.0 disablement as mentioned in the following website: https://help.salesforce.com/articleView?id=000221207&type=1

Appreciate your help very much.

Mike

**Comment by alonkama** [comment]
Yes, it's compliant with the TLS 1.0 disablement.

**Comment by mikelam2015** [comment]
Thank you for the quick response!

**Comment by mikelam2015** [comment]
@alonkama Since it is already closed I thought it is better to tag you.
Forgot to ask, is version 1.8 enough? Or do i have to update to 2.1? 
Thank you for the quick response!

**Comment by alonkama** [comment]
All versions are compatible. There are no inbound or outbound calls being made by this tool, so TLS 1.0 has no impact.

**Comment by mikelam2015** [comment]
Thank you!
