### ISSUE TITLE
user cannot see Edit Quotas tab

### ISSUE THREAD

**Issue by chrissyk** [ForceDotComLabs/QuotaEdit#53]
I have a user that cannot see the edit quota tab...permissions look right.
Thanks

**Comment by alonkama** [comment]
Did you follow this step? 
* Go to the Permission Set named 'Edit Quotas access' and assign it to the intended users

This permission set contains all the necessary permissions to see the tab.

**Comment by chrissyk** [comment]
We don't have that perm set - and it looks like we have version 1.8...which
could be an issue?

**Comment by chrissyk** [comment]
We do have a Manage Quotas perm set - can you tell me all required perms?

Thank you,
ck

**Comment by alonkama** [comment]
How about upgrading to the latest version?
If you're on the old version, you may need to grant access to the Edit Quotas Visualforce page.

**Comment by chrissyk** [comment]
Is there any way you can quickly help me with this issue? Is it best to
uninstall and reinstall an updated version?

**Comment by alonkama** [comment]
I'm in meetings all day, unfortunately, so can't jump on a call.
But yes, you can uninstall the old version and install the new version from AppExchange. There is no data loss, because Edit Quotas is just a UI over the base Salesforce capabilities.

**Comment by chrissyk** [comment]
Perfect - thank you! I'll do just that - my apologies for the urgency.

**Comment by chrissyk** [comment]
Uninstalled and reinstalled - all is good! Thank you for your help,

**Comment by alonkama** [comment]
I'm glad it worked out!
