### ISSUE TITLE
Gives an error message on upgrade / new install when historical trending is on @ forecast

### ISSUE THREAD

**Issue by makkerit** [ForceDotComLabs/QuotaEdit#58]
If your install continues to fail, contact Salesforce CRM Support through your normal channels and provide the following information.

Problem:

1. (CalendarUtil) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
CalendarUtil: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

2. (ForecastingTypeUtil) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
ForecastingTypeUtil: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

3. (LoadQuotasModel) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
LoadQuotasModel: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

4. (QuotaControllTest) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
QuotaControllTest: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

5. (QuotaController) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
QuotaController: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

6. (QuotaModel) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
QuotaModel: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

7. (RoleNodeModel) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
RoleNodeModel: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

8. (RoleUtils) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
RoleUtils: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

9. (TreeViewController) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
TreeViewController: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

10.  Apex class 'EditQuotas.TreeViewController' does not exist
TreeView: Apex class 'EditQuotas.TreeViewController' does not exist

11.  Apex class 'EditQuotas.TreeViewController' does not exist
QuotaEdit: Apex class 'EditQuotas.TreeViewController' does not exist

If you disable the historical trending it install, but as you can imagine, we can't do this on production as it deletes the history.

**Comment by alonkama** [comment]
I'm sorry for the problem in installing the package. This is a known issue with Historical Trending, and I encourage you to file a case to have it addressed. Please reference internal tracking number W-2603194.
