### ISSUE TITLE
Enable quaterly Quota 

### ISSUE THREAD

**Issue by Alpeshdpatel** [ForceDotComLabs/QuotaEdit#60]
Hi There,

I am using Edit quota app to manage quota in salesforce org. I want to enable quaterly quota functionality 
to edit quota for user. may yo please help me to resolve that issue.

Thanks,
Alpesh

**Comment by alonkama** [comment]
Switching to quarterly forecasts is possible from Setup. Please see the
online documentation or file case with Support.
The Edit Quotas app will let you enter quarterly quotas once your org is
set up for it.
