### ISSUE TITLE
I cannot install my Edit Quota app

### ISSUE THREAD

**Issue by Roryruedas** [ForceDotComLabs/QuotaEdit#62]
I receive the error below. 

1. (CalendarUtil) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
CalendarUtil: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

2. (ForecastingTypeUtil) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
ForecastingTypeUtil: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

3. (LoadQuotasModel) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
LoadQuotasModel: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

4. (QuotaControllTest) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
QuotaControllTest: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

5. (QuotaController) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
QuotaController: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

6. (QuotaModel) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
QuotaModel: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

7. (RoleNodeModel) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
RoleNodeModel: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

8. (RoleUtils) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
RoleUtils: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

9. (TreeViewController) Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem
TreeViewController: Custom Object Definition ID: bad value for restricted picklist field: ForecastingItem

10.  Apex class 'EditQuotas.TreeViewController' does not exist
TreeView: Apex class 'EditQuotas.TreeViewController' does not exist

11.  Apex class 'EditQuotas.TreeViewController' does not exist
QuotaEdit: Apex class 'EditQuotas.TreeViewController' does not exist

**Comment by alonkama** [comment]
This is the same as #58 . You will need to disable Historical trending first. You can file a case with Salesforce Support and reference that you're hitting the issue related to W-2603194.

**Comment by Roryruedas** [comment]
I have already discussed this with Salesforce support and they stated that
this is something only the third party vendor can assist with. I can
disable our historical trending report but i will lose the data we have, is
that correct.

**Comment by alonkama** [comment]
@Roryruedas in this case Salesforce support was wrong :-). 
But I just checked the status of W-2603194 and I see that it is fixed in the Winter'18 release that is rolling out by mid-October. So please try again once your account is updated by this release.

Please reopen if you're still seeing this problem in Winter'18.

**Comment by Roryruedas** [comment]
Hello Alon,

The app was finally installed and is working great! I cannot figure out how
to give other users access to edit quotas. I have given permissions to
Modify All Quota and turned the tab on yet my Sales Managers still cannot
access the object.

**Comment by alonkama** [comment]
I'm glad that it's working well for you.

See the bottom of the Readme for giving access to other users:

**For the users you want to enable:
Check their Manage Quotas and View All Forecasts perm
Go to the Permission Set named 'Edit Quotas access' and assign it to the intended users**
