### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by TreacyGrindr** [ForceDotComLabs/QuotaEdit#63]
Hello, 

I have installed this app, but I can't find the UI that you show pictures of. Where do I get access to this UI. I have read every "Read Me" file and dug around on the website.

Thanks,
Treacy

**Comment by alonkama** [comment]
Have you followed the last line of the README?
> For the users you want to enable:
> Check their Manage Quotas and View All Forecasts perm
> Go to the Permission Set named 'Edit Quotas access' and assign it to the intended users
> 
If you don't see the tab in Salesforce (even under the + symbol for More), then you have not set the permissions correctly.
