### ISSUE TITLE
Quota not populating for Forecast Manager

### ISSUE THREAD

**Issue by EricaStAngel** [ForceDotComLabs/QuotaEdit#64]
I have Forecast Hierarchy of CEO > Sales, with the single CEO user as the Forecast Manager. That individual also has his own quota, in addition to the rollup of the team. When I used Edit Quotas app to populate the quotas, all were populated except for the CEO / Forecast Manager role.

**Comment by alonkama** [comment]
Can't edit your own quota in Salesforce. It's not a limitation of the AppExchange app.
If you want CEO to do it, give them View All Forecasts.

**Comment by EricaStAngel** [comment]
Different issue. I'm uploading quota for all reps, and View All Forecasts is enabled for all sales users. I believe the issue is another limitation of Salesforce: https://help.salesforce.com/articleView?id=Not-seeing-quota-for-my-own-opportunities-Collaborative-Forecasting&language=en_US&type=1

**Comment by alonkama** [comment]
OK. So this is unrelated to this app. I'll close the thread, then.
