### ISSUE TITLE
Add/Remove Names

### ISSUE THREAD

**Issue by lspano** [ForceDotComLabs/QuotaEdit#65]
How can you add/remove a person from the quota list? It automatically pulls in names but I am not sure where the list is pulling from. Some are old and the new ones are not on there.

**Comment by alonkama** [comment]
See https://github.com/ForceDotComLabs/QuotaEdit/blob/master/src/classes/RoleUtils.cls#L21 . It pulls all active forecasting-enabled users. If you have permissions to view all, it brings all. Otherwise, it's based on the ones underneath the current user in the Role Hierarchy.
