### ISSUE TITLE
Sales agents can not enter his quota in the QuotaEdit Page

### ISSUE THREAD

**Issue by requiemnameless** [ForceDotComLabs/QuotaEdit#66]
Our sales agents can access QuotaEdit page. When they click "Fetch Quotas", result does not appear.

But sales manager can access and edit their team's quotas, they use same profile(check "Manage Quotas"only).

If I check "View All Forecasts", sales agent can see all quotas include others. Is that the only way?

**Comment by alonkama** [comment]
Sales agents cannot edit their own quota. This is by design in Salesforce Collaborative Forecasting. This app cannot change this limitation.
