### ISSUE TITLE
Only Admins Able to Edit Quotas

### ISSUE THREAD

**Issue by ResyConnor** [ForceDotComLabs/QuotaEdit#69]
I'm having an issue where my Head of Sales cannot edit the team quotas. She is not listed as an admin in Salesforce, but is the highest user in Roles and the forecast rolls up under her name. 

Any idea why this is happening? I've installed the app for all users and she still cannot see it.

**Comment by alonkama** [comment]
@ResyConnor have you tried following the Installation Instructions here: https://github.com/ForceDotComLabs/QuotaEdit#installation-instructions ? They describe how to enable users to be quota editors.

**Comment by alonkama** [comment]
I'm assuming this is resolved. If not, please reopen and mention whether you followed those instructions.
