### ISSUE TITLE
Can I install Edit Quotas on my Sandbox?

### ISSUE THREAD

**Issue by sarahnarleen** [ForceDotComLabs/QuotaEdit#70]
The download option only lets me log into Production

**Comment by alonkama** [comment]
I'm not sure how you're deploying, but the URL for sandbox is test.salesforce.com . 
The ideal way to install is from AppExchange. So from the sandbox, go to Setup and then AppExchange, and look for this app.

**Comment by sarahnarleen** [comment]
I am logged into the sandbox. I am accessing the AppExchange through
Salesforce, but it still requires me to login.  When I click login, I only
have the option to login to Production. How can I log into Sandbox?




*Sarah Ramnath, MBA*

*Engagement Manager*

C: 647-880-7181

E: sarah.ramnath@stratus360.com

W: www.Stratus360.com <http://www.stratus360.com/>

**Comment by alonkama** [comment]
You should log with your production credentials. Later, on the acknowledgement screen to install the package, you'll see that the username is actually your sandbox username.

**Comment by alonkama** [comment]
Hopefully this resolved your issue. If not, please reopen with more information.
