### ISSUE TITLE
Forecasting figures doubled

### ISSUE THREAD

**Issue by levarbackbone** [ForceDotComLabs/QuotaEdit#73]
Hi, the figures that I've entered within salesforce seems to double themselves whenever I create a report and display it on a dashboard in salesforce.

**Comment by alonkama** [comment]
This doesn't sound like a problem with the Edit Quotas app.
See best practices for creating a forecast report here:
https://help.salesforce.com/articleView?id=000205359&type=3
and here:
https://resources.docs.salesforce.com/latest/latest/en-us/sfdc/pdf/forecasts.pdf
