### ISSUE TITLE
Role Hierarchy required?

### ISSUE THREAD

**Issue by KristinLucas147** [ForceDotComLabs/QuotaEdit#74]
Is a role hierarchy required to configure quotas for Sales Reps?

**Comment by alonkama** [comment]
This question is unrelated to this Labs app. For Forecasting setup help, please see Salesforce Help&Training. This guide is helpful: https://resources.docs.salesforce.com/212/latest/en-us/sfdc/pdf/forecasts.pdf

**Comment by KristinLucas147** [comment]
The reason I asked is because I installed the app but cannot figure out how to add quotas.

This is what I see on the Edit Quotas screen:

![image](https://user-images.githubusercontent.com/39809479/40804196-721e123a-64cf-11e8-9646-b2923c17bc0f.png)
